Script started on 2019年03月 4日 下午 06:36:16
]0;~
[32mymgs1@MSI [33m~[0m
$ whoami;pwd
ymgs1
/home/ymgs1
]0;~
[32mymgs1@MSI [33m~[0m
$ git.[K config -l
[?1h=user.name=kingdomliife[m
user.email=ymgs1522@gmail.com[m
[K[?1l>]0;~
[32mymgs1@MSI [33m~[0m
$ git clone https://github.com/kingdomliife/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32mymgs1@MSI [33m~[0m
$ exit

Script done on 2019年03月 4日 下午 06:37:23
